import { PrinterIcon } from "@phosphor-icons/react";
import { Panel } from "~/components/ui/panel";
import { Button } from "~/components/ui/button";
import { EvidenceMetric } from "~/components/evidence/evidence";
import { DataQualityPanel } from "~/components/evidence/data-quality";
import { assetExposureById, assets, batteryScenarios, dataQualityByAsset } from "~/domain/fixtures";
import { formatEvidence } from "~/lib/format";
import { useAnalysis } from "~/state/use-analysis";
import type { EvidenceValue } from "~/domain/types";

export function ReportScreen() {
  const { state } = useAnalysis();
  const asset = assets.find((item) => item.id === state.assetId) ?? assets[0];
  const exposure = assetExposureById[asset.id];
  const maintenance = state.maintenanceAnalysis?.assetId === asset.id ? state.maintenanceAnalysis : null;
  const decision = state.decision?.assetId === asset.id ? state.decision : null;
  const selected = decision && maintenance ? maintenance.windows.find((item) => item.id === decision.selectedWindowId) ?? null : null;
  const batterySelection = state.batterySelection?.assetId === asset.id ? state.batterySelection : null;
  const battery = batterySelection ? batteryScenarios.find((item) => item.id === batterySelection.scenarioId && item.residualProfileId === batterySelection.residualProfileId && item.mode === batterySelection.mode) ?? null : null;
  const quality = dataQualityByAsset[asset.id] ?? dataQualityByAsset["asset-wind"];
  const solar = asset.id === "asset-solar";

  return <div className="mx-auto max-w-5xl space-y-5"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-line pb-5"><div><h1 className="text-3xl font-semibold">Relatório da decisão</h1><p className="mt-2 text-sm text-ink-soft">Consolidação imprimível do que foi analisado e registrado nesta sessão.</p></div><Button className="no-print" variant="primary" onClick={() => window.print()}><PrinterIcon aria-hidden="true" />Imprimir relatório</Button></header>
    <Panel title="Identificação"><dl className="grid gap-3 sm:grid-cols-3"><Item label="Ativo" value={asset.name} /><Item label="Tecnologia" value={asset.technology} /><Item label="Versão dos dados" value={quality.dataVersion} /></dl></Panel>
    <Panel title="Exposição histórica"><EvidenceMetric label="Energia não realizada" evidence={exposure.summary.total} /></Panel>
    {maintenance ? <>
      <Panel title="Parâmetros da intervenção"><dl className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Item label="Duração" value={`${maintenance.request.duration} horas`} /><Item label="Intervalo elegível" value={`${maintenance.request.start} a ${maintenance.request.end}`} /><Item label="Antecedência" value={`${maintenance.request.notice} dias`} /><Item label="Janela-base" value={maintenance.request.baseline} /><Item label="Indisponibilidades" value={maintenance.request.unavailable} /><Item label="Restrições operacionais" value={maintenance.request.operationalNotes} /></dl><p className="mt-4 text-xs text-ink-soft">Fonte: formulário do cliente. Estado: informado pelo cliente. Período: cenário de outubro de 2026. Versão: sessão atual.</p></Panel>
      <Panel title="Ranking consultado"><div className="max-w-full overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><caption className="sr-only">Alternativas de manutenção realmente consultadas na sessão</caption><thead><tr><th scope="col" className="border-b border-line p-3">Alternativa</th><th scope="col" className="border-b border-line p-3">Curtailment esperado</th><th scope="col" className="border-b border-line p-3">Perda</th><th scope="col" className="border-b border-line p-3">Diferença energética</th><th scope="col" className="border-b border-line p-3">Diferença monetária</th><th scope="col" className="border-b border-line p-3">Estado</th></tr></thead><tbody>{maintenance.windows.filter((window) => window.eligible).map((window) => <tr key={window.id} className={selected?.id === window.id ? "bg-accent-soft" : ""}><td className="border-b border-line/70 p-3 font-semibold">{window.baseline ? "Janela-base" : `Alternativa ${window.rank}`}</td><td className="num border-b border-line/70 p-3">{formatEvidence(window.expectedCurtailment.value, window.expectedCurtailment.unit)}</td><td className="num border-b border-line/70 p-3">{formatEvidence(window.interventionLoss.value, window.interventionLoss.unit)}</td><td className="num border-b border-line/70 p-3">{formatEvidence(window.differenceFromBaseline.value, window.differenceFromBaseline.unit)}</td><td className="num border-b border-line/70 p-3">{formatEvidence(window.monetaryDifferenceFromBaseline.value, window.monetaryDifferenceFromBaseline.unit)}</td><td className="border-b border-line/70 p-3">{window.interventionLoss.state}</td></tr>)}</tbody></table></div><dl className="mt-3 grid gap-2 text-xs leading-5 text-ink-soft sm:grid-cols-2"><MethodItem label="Curtailment esperado" evidence={maintenance.windows[0].expectedCurtailment} /><MethodItem label="Perda" evidence={maintenance.windows[0].interventionLoss} /><MethodItem label="Diferença energética" evidence={maintenance.windows[0].differenceFromBaseline} /><MethodItem label="Diferença monetária" evidence={maintenance.windows[0].monetaryDifferenceFromBaseline} /></dl></Panel>
      <Panel title="Decisão registrada">{decision && selected ? <dl className="grid gap-3 sm:grid-cols-2"><Item label="Janela escolhida" value={selected.baseline ? "Base mantida" : `Alternativa ${selected.rank}`} /><Item label="Data da decisão" value={new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(decision.recordedAt))} /><DecisionEvidence label="Diferença energética" evidence={decision.energyDifference} /><DecisionEvidence label="Diferença monetária" evidence={decision.monetaryDifference} /><Item label="Justificativa" value={decision.justification} /><Item label="Perfil residual" value={decision.residualProfileId} /></dl> : <p className="text-sm text-ink-soft">O ranking foi consultado, mas nenhuma janela foi registrada como decisão. Diferenças de decisão e perfil residual permanecem indisponíveis.</p>}</Panel>
    </> : <Panel title="Análise de manutenção não realizada" description="Nenhum formulário foi enviado nesta sessão. Parâmetros, ranking, diferenças e decisão permanecem indisponíveis." />}
    {battery ? <Panel title="Triagem de bateria registrada"><dl className="mb-4 grid gap-3 sm:grid-cols-3"><Item label="Modo" value={battery.mode === "new" ? "Bateria nova" : "Bateria existente"} /><Item label="Cenário" value={battery.id} /><Item label="Perfil residual" value={battery.residualProfileId} /></dl><div className="grid gap-3 sm:grid-cols-3"><EvidenceMetric label="Residual" evidence={battery.residualEnergy} /><EvidenceMetric label="Potencialmente absorvível" evidence={battery.absorbableEnergy} /><EvidenceMetric label="Lacuna econômica" evidence={battery.economicGap} /></div><p className="mt-4 text-sm text-ink-soft">Triagem econômica preliminar registrada explicitamente; despacho ainda não validado.</p></Panel> : <Panel title="Triagem BESS não registrada" description="Nenhum cenário de bateria foi registrado para este ativo. O relatório não preenche uma configuração padrão." />}
    <DataQualityPanel quality={quality} />
    <Panel title="Fontes, premissas e limitações"><ul className="list-disc space-y-2 pl-5 text-sm text-ink-soft"><li>{solar ? "Caso solar composto por fixture sintética da API CurtailLess." : "Histórico do Portal de Dados Abertos do ONS, lido pelo backend."}</li><li>Preço de energia e reservas são parâmetros simulados.</li><li>Perspectiva de 30 dias é histórica e sazonal.</li><li>Sem meteorologia ex ante, telemetria real, SOC cronológico ou limite operativo do ponto.</li></ul><p className="mt-4 break-all text-xs text-ink-soft">Identificador de versão: report-demo-20260926 | Hash demonstrativo: pendente de geração server-side</p></Panel>
  </div>;
}
function MethodItem({ label, evidence }: { label: string; evidence: EvidenceValue }) { return <div><dt className="font-semibold text-ink">{label}</dt><dd>Método: {evidence.method} Período: {evidence.period.label}. Fonte: {evidence.source}. Versão: {evidence.dataVersion}. Estado: {evidence.state}.</dd></div>; }
function DecisionEvidence({ label, evidence }: { label: string; evidence: EvidenceValue }) { return <div><dt className="sr-only">{label}</dt><dd><EvidenceMetric label={label} evidence={evidence} /></dd></div>; }
function Item({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-ink-soft">{label}</dt><dd className="mt-1 break-words font-semibold">{value}</dd></div>; }
